### ISSUE TITLE
Question about positional encoding

### ISSUE THREAD

**Issue by luyangzhu** [bmild/nerf#65] opened 2020-07-28 19:00 UTC
Thank you for your nice work and impressive results!

I have a question about the positional encoding. In the equation (4) of the paper, input is multiplied by pi before sent into sine and cosine function. But in the run_nerf_helper.py, the class Embedder do not times pi before applying sine and cosine. Did I miss something or the pi does not affect results that much?

**Comment by kwea123** [comment] 2020-07-29 01:47
duplicate of #12

**Closed** 2020-07-29 02:17 UTC
